// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  card

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Card ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Card ) UnmarshalJSON([]byte) error { return nil }
func ( Card ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Card ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Card *Card
