// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  board

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Board ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Board ) UnmarshalJSON([]byte) error { return nil }
func ( Board ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Board ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Board *Board
