// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package board

import (
	customType "2019_2_Shtoby_shto/src/customType"
	cardGroup "2019_2_Shtoby_shto/src/dicts/cardGroup"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecode20192ShtobyShtoSrcDictsBoard(in *jlexer.Lexer, out *Board) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "board_users_id":
			out.BoardUsersID = customType.StringUUID(in.String())
		case "card_groups":
			if in.IsNull() {
				in.Skip()
				out.CardGroups = nil
			} else {
				in.Delim('[')
				if out.CardGroups == nil {
					if !in.IsDelim(']') {
						out.CardGroups = make([]cardGroup.CardGroup, 0, 1)
					} else {
						out.CardGroups = []cardGroup.CardGroup{}
					}
				} else {
					out.CardGroups = (out.CardGroups)[:0]
				}
				for !in.IsDelim(']') {
					var v1 cardGroup.CardGroup
					(v1).UnmarshalEasyJSON(in)
					out.CardGroups = append(out.CardGroups, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "id":
			out.ID = customType.StringUUID(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncode20192ShtobyShtoSrcDictsBoard(out *jwriter.Writer, in Board) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"board_users_id\":"
		out.RawString(prefix)
		out.String(string(in.BoardUsersID))
	}
	{
		const prefix string = ",\"card_groups\":"
		out.RawString(prefix)
		if in.CardGroups == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.CardGroups {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Board) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncode20192ShtobyShtoSrcDictsBoard(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Board) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncode20192ShtobyShtoSrcDictsBoard(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Board) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecode20192ShtobyShtoSrcDictsBoard(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Board) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecode20192ShtobyShtoSrcDictsBoard(l, v)
}
